/*!
 * Filename: ditaarch_schema.js
 * License: MIT License - https://opensource.org/licenses/MIT
 * Copyright (c) 2025 MITIM Professional Services DOO
 * JSON Schema. 2020-12 Release
 * Generated by the MITIM XML Editor, version: 1.3.111
 */

import { ap, o } from './common_xml_schema.js';

export const ditaarch = {
    "$defs": {
    },
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    ...ap,
    "properties": {
     },
    "type": o
}
export default ditaarch;
