/*!
 * Filename: highlightDomain_schema.js
 * License: MIT License - https://opensource.org/licenses/MIT
 * Copyright (c) 2025 MITIM Professional Services DOO
 * JSON Schema. 2020-12 Release
 * Generated by the MITIM XML Editor, version: 1.3.111
 */

import { ap, o, ts } from './common_xml_schema.js';

const b_comTp0 = {
    "@outputclass": ts,
    "@class": ts,
    "editor__________node_______schema___": {
        "name": "b_comTp0",
        "attrs": {
            "@class": "+ topic/ph hi-d/b "},
        "props": [
        ]
    },
}
const b2 =  {
    "$ref": "#/$defs/.b_comTp0",
}
const i1 =  {
    "$ref": "#/$defs/.b_comTp0",
}
const u1 =  {
    "$ref": "#/$defs/.b_comTp0",
}
const sup1 =  {
    "$ref": "#/$defs/.b_comTp0",
}
const sub1 =  {
    "$ref": "#/$defs/.b_comTp0",
}
export const highlightDomain = {
    "$defs": {
        ".b_comTp0": {
            ...ap,
            "properties": b_comTp0,
            "type": o
        },
        ".b2": b2,
        ".i1": i1,
        ".u1": u1,
        ".sup1": sup1,
        ".sub1": sub1,
    },
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    ...ap,
    "properties": {
        "b": {
            "$ref": "#/$defs/.b2",
        },
        "i": {
            "$ref": "#/$defs/.i1",
        },
        "u": {
            "$ref": "#/$defs/.u1",
        },
        "sup": {
            "$ref": "#/$defs/.sup1",
        },
        "sub": {
            "$ref": "#/$defs/.sub1",
        },
     },
    "type": o
}
export default highlightDomain;
